### ISSUE TITLE
ISBN citation of books

### ISSUE THREAD

**Issue by dhimmel** [greenelab/manubot#14]
While many scholarly books have DOIs, there are lot's of books out there with just ISBNs. As a standardized identifier, they seem appropriate for Manubot book citations. We discussed the issue in https://github.com/greenelab/deep-review/issues/387 and found serveral ISBN lookup services.

However, none of them are aware of the [2012 Open Access Book](https://mitpress.mit.edu/books/open-access) indicating poor coverage:

+ https://isbnsearch.org/isbn/9780262302524
+ http://isbndb.com/search/all?query=9780262302524
+ http://xisbn.worldcat.org/webservices/xid/isbn/9780262302524?method=getMetadata&format=xml&fl=*

**Update**: I think `9780262302524` is the wrong ISBN, but was listed on the MIT Press website.

@agapow commented:

> My impression of worldcat and isbndb is that there's quite a lag before titles get listed (and they may never get listed). Not a solution, but we probably need another way.

So the purpose of this issue is to note that ISBN citation would be valuable and to track any potential solutions.

**Comment by dhimmel** [comment]
Just came across https://github.com/xlcnd/isbntools a python package which can retrieve metadata from ISBNs.

**Comment by agitter** [comment]
To follow up on https://github.com/greenelab/manubot/issues/70#issuecomment-429294166, I tested the Open Access book in Citoid and it worked:
https://en.wikipedia.org/api/rest_v1/data/citation/mediawiki/9780262517638

```
[
  {
    "itemType": "book",
    "date": "2012",
    "publisher": "MIT Press",
    "title": "Open access",
    "oclc": "795846161",
    "url": "https://www.worldcat.org/oclc/795846161",
    "ISBN": [
      "9780262301732",
      "0262301733"
    ],
    "place": "Cambridge, Massachusetts",
    "numPages": "1 online resource (xii, 242 pages)",
    "abstractNote": "A concise introduction to the basics of open access, describing what it is (and isn't) and showing that it is easy, fast, inexpensive, legal, and beneficial",
    "author": [
      [
        "Suber,",
        "Peter,"
      ]
    ],
    "accessDate": "2018-10-12",
    "source": [
      "WorldCat"
    ]
  }
]
```

**Comment by dhimmel** [comment]
# Testing ISBNs

I found this [gist of 500 ISBNs](https://gist.github.com/adrianshort/1253715), which could be handy for testing purposes.
