### ISSUE TITLE
Email address treated as citation causing error

### ISSUE THREAD

**Issue by dhimmel** [greenelab/manubot#25]
The following source:

```
To whom correspondence should be addressed: gitter@biostat.wisc.edu (AG) and csgreene@upenn.edu (CSG)
```

caused the following error

```
## ERROR
Citation not splittable: @upenn.edu
## ERROR
Citation not splittable: @biostat.wisc.edu
```

The citation extractor is treating `@upenn.edu` and `@biostat.wisc.edu` like citations.

**Comment by agitter** [comment]
We can work around this for now.  Will the eventual fix be to modify the [`citation_pattern`](https://github.com/greenelab/manubot/blob/b53f487026954729ce80ca963f3838ebca85a144/manubot/citations.py#L23)?

**Comment by dhimmel** [comment]
@agitter the two relevant parts of the code are:

https://github.com/greenelab/manubot/blob/b53f487026954729ce80ca963f3838ebca85a144/manubot/citations.py#L23-L24

https://github.com/greenelab/manubot/blob/33e512d21218263423de5f0d127aac4f8635468f/manubot/manuscript.py#L15

Any easy fix would be to lookbehind to make sure the `@` was proceeded by `[`, whitespace, or start of line. However, an alternative longterm solution would try to rely on pandoc's parser more here. That would help address related issues like https://github.com/greenelab/manubot/issues/13.

**Comment by dhimmel** [comment]
Two options:

Positive Lookbehind
`((?<=[([\s])|(?<=^))`
Requires or logic for when the document starts with a citation.
https://regex101.com/r/OOATKN/1

Negative lookbehind
`(?<!\w)`
https://regex101.com/r/s3Asz3/1

I think I like the negative for its simplicity. This regex will not match `@` if preceded by a word character (`[a-zA-Z0-9_]`). This will take care of most email addresses. Possible some unresolved issues, but I think that's preferable to going too far.

**Comment by agitter** [comment]
> I think I like the negative for its simplicity

Me too.  I was happy with the behavior in your test cases in #27 and the others I tried.
