### ISSUE TITLE
Setting time zone to get the correct build date

### ISSUE THREAD

**Issue by slochower** [greenelab/manubot#3]
I'm getting...

"This manuscript was automatically generated from xxx@355c47e on August 6, 2017."

...for dates in the future (today is August 5th, to be clear).  I was particularly confused because builds around 1 PM local time today reported tomorrow's date. From what I can gather, the date template in the front matter is replaced by
```python
# Add date to metadata
today = datetime.date.today()
metadata['date-meta'] = today.isoformat()
stats['date'] = today.strftime('%B %e, %Y')
```
...which I assume is using the time zone set by the system. I think we can fix this by setting
```
before_install:
- export TZ=Australia/Canberra
```
...in `travis.yaml` but I haven't checked. However, it remains unclear which time zone to set. Ideally there could be a way to set the container time zone from the GitHub/Travis account. What are your thoughts?

**Comment by dhimmel** [comment]
@slochower, we should ensure that CI builds always use the same time zone and that all dates reported (`date-meta` in the yaml_metadata_block and `date` in `variables.tsv`) are based on this time zone.

One option would be to use [Coordinated Universal Time](https://en.wikipedia.org/wiki/Coordinated_Universal_Time) (UTC). Perhaps, if maintainers would like, they can switch to a project specific timezone.

Ideally, a single variable (for example from `.travis.yml`) would set the timezone that CI builds as well as local builds would adhere to. But this probably isn't worth too much code complexity overhead. So I think the main priority is to ensure that CI builds adhere to a consistent, specified timezone.

@slochower what are your thoughts? Want to take the lead here?

Some possible options:

+ Setting the timezone explicitly in `.travis.yml`
+ Setting the timezone in `metadata.yaml`

**Comment by slochower** [comment]
I'm fine with leaving everything UTC, as that is surely the easiest and least complicated, and then my only suggestion is to add the time zone to the string template that gets written to `manuscript.md`. That goes towards the comment in your edit.

**Comment by dhimmel** [comment]
Let's add the following to `before_install` in `.travis.yml`:

```
- export TZ=Etc/UTC
```

References:
+ https://stackoverflow.com/a/27052708/4651668
+ https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

> my only suggestion is to add the time zone to the string template that gets written to `manuscript.md`.

We could extract the timezone abbreviation in python using `time.tzname[time.daylight]`.

Or in [this line](https://github.com/greenelab/manubot/blob/1723a22ebb7dce98e60fd748f4e6c5380e6ce08c/manubot/manubot.py#L155), we could do the more intricate:

```
import datetime
# Create a timezone aware datetime. See https://stackoverflow.com/a/39079819/4651668
local_timezone = datetime.datetime.now(datetime.timezone.utc).astimezone().tzinfo
time_now = datetime.datetime.now(local_timezone)
time_now.strftime('%B %e, %Y %Z')  # save to variables['date']
```

This method would make `variables['date']` like `August 10, 2017 EDT`. But is it customary to display the timezone next to just dates?

@agitter what do you think?

**Comment by agitter** [comment]
I like the idea of making sure the time zone is standardized in CI builds.  I don't often see time zones displayed with dates though.  In particular, the date stamps added to bioRxiv and arXiv pdfs are related examples that don't have time zones.

@slochower if this behavior was described in `USAGE.md` in `manubot-rootstock` would it have been less confusing?  We could standardize the time zone and describe where it is set in `.travis.yml` instead of adding the time zone to the date stamp.

**Comment by slochower** [comment]
@agitter Yes, this sounds good -- mention it in `USAGE.md` and allow the user to specify in `.travis.yml`.
