### ISSUE TITLE
`get_citation_strings` seems to be incorrectly matching non-citations with `@`

### ISSUE THREAD

**Issue by slochower** [greenelab/manubot#33]
I am having a problem with non-citations containing `@` being matched and then failing. This is surprising because the `citation_pattern` regex does *not* match my string (correctly).

I have a file `00-tmp.md` that contains the single line:
```
parm@Frosst is a force field.
```
If I run `manubot`:

```bash
$ manubot --content-directory=./ --output-directory=./
## ERROR
Citation not splittable: @Frosst
```
As expected, if I delete the `@` sign then this goes away.

I think that `is_valid_citation_string` is being called, stripping the `@` then looking to split at `:` which isn't in my string, hence the error. Here's the surprising part (to me). The things sent to `is_valid_citation_string` come from looking for the `citation_pattern` regex in the text and my string shouldn't match the regex, right?

https://github.com/greenelab/manubot/blob/27456594c407f3fed35804db4bcf3b5bba88a716/manubot/manuscript.py#L11-L17

**Comment by slochower** [comment]
Just to confirm my string doesn't `citation_pattern`:

```python
In [2]: import re

In [3]: citation_pattern = re.compile(
   ...:    ...:     r'(?<!\w)@[a-zA-Z0-9][\w:.#$%&\-+?<>~/]*[a-zA-Z0-9/]')
   ...:

In [4]: print(citation_pattern.match('@doi:99999'))
<_sre.SRE_Match object; span=(0, 10), match='@doi:99999'>

In [5]: print(citation_pattern.match('parm@Frosst'))
None
```

**Comment by slochower** [comment]
Ah, even though `citation_pattern.match('parm@Frosst')` returns `None`, `findall` gives a different result:
```python
In [8]: citation_pattern.findall('parm@Frosst')
Out[8]: ['@Frosst']
```

**Comment by agitter** [comment]
@slochower this is confusing to me, because the behavior you're describing seems to be the same behavior we saw in #25 with email addresses.  That was fixed in #27 with the new `citation_pattern`.

Are you seeing the `Citation not splittable: @Frosst` error locally, in a Travis build, or both?

**Comment by slochower** [comment]
The error is local. I'm writing peer-review notes on some papers, so I don't want or need the whole `manubot-rootstock` system and am leveraging standalone `manubot` -- I made a little build script for my text editor that will copy the currently open Markdown buffer to /tmp, run `manubot` and then `pandoc` there, and open the HTML in a browser. It's handy for writing quick things where I need to cite other papers.

I just did more digging comparing the output of matching strings with pure python (i.e., just using `import re`) and with `manubot.get_citation_strings()`. You left me a good hint by mentioning that the citation regex changed in #27. 

I'll go straight to the point: even if I make a new clone of the `manubot` repository and run `pip install .` there, when I run ` from manubot.citations import citation_pattern`, I get the old citation pattern -- `re.compile('@[a-zA-Z0-9][\\w:.#$%&\\-+?<>~/]*[a-zA-Z0-9/]')` -- and this is the string before #27. I think this is because `manubot.__version__` is set to 0.0.0 in both the existing installation and in the new directory. This is, unfortunately, not apparent at all from the `pip` output, which threw me off thinking the automatic upgrade I intended was successful:
```bash
  Running setup.py bdist_wheel for manubot ... done
  Stored in directory: /Users/dslochower/Library/Caches/pip/wheels/ad/15/81/56d818c53bd871b8fe932acdb91f09d6d99a0fd86ca16bee10
Successfully built manubot
```

 The good news is that I can force this to work by simply running `pip install --upgrade .`, which I probably should have tried in the first place. And I know I can always force `pip` to install a specific commit, but in this case, I didn't want that. So I'd say, case closed for now.

**Comment by dhimmel** [comment]
If I remember correctly from my pip experience, pip never upgrades without the `--upgrade` flag. From the [pip docs](https://pip.pypa.io/en/latest/reference/pip_install/):

> Note that if a satisfactory version of the package is already installed, the VCS source will not overwrite it without an --upgrade flag. So I don't think it has to do with us not incrementing `manubot.__version__`.

@slochower how would you feel about a docker image, so you could pull the latest docker image and it'd have the latest manubot program?

**Comment by slochower** [comment]
Maybe overkill, but it's not a bad idea. Are you thinking this would avoid people thinking they have the latest version but actually not (like I mistakenly did)?

**Comment by agitter** [comment]
@slochower I believe the incentive for Docker would be a combination of what you noted -- ensuring the latest Manubot version -- and because we're seeing more dependencies on fonts or libraries that must be present outside the conda environment.

**Comment by slochower** [comment]
In that case, it's probably worthwhile. I'm happy to test out an image. 

I've only really used Docker for one other project and we gradually stopped using the containers because it was a pain to get files into and out of the container (e.g., convoluted mounting commands with permission issues). This may very well be better now. Will it be easy to have a local markdown document get passed to the container process and have the output pass again out of the container?

**Comment by dhimmel** [comment]
> would avoid people thinking they have the latest version but actually not

Hopefully the versioning of the docker images would be a bit more concrete and easier to specify a specific version than with the current conda environment.

> Will it be easy to have a local markdown document get passed to the container process and have the output pass again out of the container?

We'd probably end up mapping some volumes like content and output. Will open a new issue or PR to discuss this further.
