### ISSUE TITLE
TypeError: argument of type 'WindowsPath' is not iterable

### ISSUE THREAD

**Issue by Sieboldianus** [greenelab/manubot#34]
I got the following error when running `pytest`:

```python
>           needquote = (" " in arg) or ("\t" in arg) or not arg
E           TypeError: 'WindowsPath' object is not iterable
TypeError: argument of type 'WindowsPath' is not iterable
...\Miniconda3\envs\manubot-dev\lib\subprocess.py:461: TypeError
```

I fixed this by [converting path to str](https://www.scivision.co/windows-python-pathlib-subprocess-bug/):
Line 461: `needquote = (" " in str(arg)) or ("\t" in str(arg)) or not str(arg)`
Line 465: `for c in str(arg):`

.. according to [this suggestion](https://groups.google.com/d/msg/python-gnupg/TUIUHmq_OA8/YpoKh-6NAQAJ). 

My programming background is pretty limited and I am not sure whether this solution fits for all, thus I am sharing it here (and not directly committing).

**Comment by dhimmel** [comment]
Refs https://bugs.python.org/issue33617... wow, a pretty annoying bug for core python. Looks like there's a [PR open](https://github.com/python/cpython/pull/7071) to fix it, but that won't be available until at least 3.8. So let's fix this before then.

I'd suggest wrapping the following pathlib.Path objects in `str`:

https://github.com/greenelab/manubot/blob/33ff36728e23f3c685f3b00a6a26f19a6fcbf68e/tests/test_manubot.py#L27-L28

https://github.com/greenelab/manubot/blob/33ff36728e23f3c685f3b00a6a26f19a6fcbf68e/tests/test_manubot.py#L33

@Sieboldianus do you want to make a PR to do that?

I'm not sure whether there will be other issues with running the `manubot` package on windows. I don't think we've decided whether this package officially supports windows, but if it's just a few small fixes like this, we might as well for the time being.

**Comment by agitter** [comment]
Thanks for reporting this @Sieboldianus.

If we want to support Windows or test the feasibility of Windows support, we could consider adding AppVeyor for continuous integration testing.  I haven't checked recently whether Travis supports Windows, but not too long ago I saw recommendations for Travis + AppVeyor for testing multiple platforms.

**Comment by dhimmel** [comment]
https://github.com/greenelab/manubot/pull/35 now tests this repository on windows, so the `manubot` CLI should be windows compatible.

@Sieboldianus setting up the travis infrastructure of manubot-rootstock currently doesn't work on Windows due to an upstream issue. Looks like you're hitting another issue, perhaps related to the symbolic links. Anyways, if you elaborate about your desired use case, perhaps we can support it or find an acceptable workaround.
