### ISSUE TITLE
Raw citation option to directly cite a CSL entry in manual-references.json

### ISSUE THREAD

**Issue by dhimmel** [greenelab/manubot#62]
Currently, you can manually specify CSL for a reference in `manual-references.json`. However, the reference still has to be identified in terms of a standard identifier, such as a URL, DOI, or other resource ID.

This hasn't been a huge issue since most references have a URL of some sort. However, that may not always be the case, such as a personal communication or some physical resource. This issue proposes adding a way to add a "raw" citation that gets directly looked up in `manual-references.json`. Raw citations must have their CSL defined in `manual-references.json`.

One reason we didn't add this feature initially is that we wanted to encourage citing things by their standard identifiers. We didn't want users to fallback to citing things without standard identifiers. However, I think the benefits to raw citations outweigh. In addition to allowing citation of URL-less records, it could help us with testing, where we want to evaluate citation of many different types of CSL entries in `manual-references.json`.

Two citation string implementation come to mind: `@raw:raw-id-here` or `@raw-id-here`. The `manual-references.json` CSL would then have to set `id: raw-id-here` or `standard_citation: "raw:raw-id-here"`.

@agitter what do you think?

**Comment by agitter** [comment]
I also see the need for a raw citation.  Hopefully it would not be overused because the automated citation will still be more convenient for most types of references.

The citation string `@raw:raw-id-here` seems more natural to me in the context of the other types of citations.  I also prefer `standard_citation: "raw:raw-id-here"` because manually overriding a reference also involves modifying the `standard_citation` key.

**Comment by dhimmel** [comment]
> The citation string `@raw:raw-id-here` seems more natural to me in the context of the other types of citations.  I also prefer `standard_citation: "raw:raw-id-here"` because manually overriding a reference also involves modifying the `standard_citation` key.

Okay, turns out the implementation of this method is rather straightforward. See https://github.com/greenelab/manubot/pull/74
