### ISSUE TITLE
Terminal recording to demonstrate manubot cite functionality

### ISSUE THREAD

**Issue by dhimmel** [greenelab/manubot#63]
I'd like to create some screen recordings of terminal sessions demonstrating our `manubot cite` functionality.

There are a lot of choices for making terminal recordings, and after looking at a [comprehensive guide](https://intoli.com/blog/terminal-recorders/), I think https://asciinema.org will meet our needs. This service creates recordings (casts) that are viewable in a javascript web-player. In addition, there are utilities to convert casts [to GIFs](https://github.com/asciinema/asciicast2gif/issues/44#issuecomment-427653887) and [to animated SVGs](https://github.com/marionebl/svg-term-cli/).

**Comment by dhimmel** [comment]
Second draft at https://asciinema.org/a/Xu42YXZyFmVfwQRT4rBdRpuml

**Comment by slochower** [comment]
I can review on Monday. Thanks for keeping the updates coming.

**Comment by agitter** [comment]
This is really great.  It's an excellent way to showcase the new manubot command line functionality.  I agree it should go in the README.

Draft 3 looks good to me.  The only part that could possibly be modified is `manubot cite url:https://greenelab.github.io/meta-review/`.  The CSL is too long to fit in the terminal so it may not be obvious to viewers that the date, title, etc. are also returned.  Piping the output to `less` may work, but I'm not sure how that would look in asciinema.  Another option would be to use a single author reference as an example.

That's a minor suggestion.  I'm also happy using draft 3 if recording and converting these is tedious.

**Comment by dhimmel** [comment]
@agitter I like your less idea. We could even syntax highlight the JSON like:

```
manubot cite url:https://greenelab.github.io/meta-review/ | jq -C . | less
```

**Comment by dhimmel** [comment]
I think I got a good one at https://asciinema.org/a/205085?speed=2. Notice how the URL change from content-addressed to an ID number cause I made it public. Also I set the speed to 2x. I'll update https://github.com/greenelab/manubot/pull/64 with this recording.

**Comment by agitter** [comment]
> I think I got a good one at https://asciinema.org/a/205085?speed=2

Yes, this one looks perfect.  It's much easier to see what is in the JSON file with the slight pause and syntax highlighting.

**Comment by slochower** [comment]
This looks good. Are there extra blank lines in your terminal after hitting enter? Not a big deal.

I think this is good demonstration, but if you were to do it again, I would add the `render` commands first, because I think that's a more common use-case than generating JSON.

**Comment by dhimmel** [comment]
> Are there extra blank lines in your terminal after hitting enter?

Yeah I did some blank lines to help separate things.

> I would add the render commands first, because I think that's a more common use-case than generating JSON.

Yeah good point. My thinking was that I wanted to demonstrate a bit how the program worked... first by retrieving the CSL and second by rendering it. Not sure it's worth the energy to reorder it now, but will keep this in mind for future recordings.

**Comment by dhimmel** [comment]
I am going to merge. We can update recording in future as needed, so feedback still welcome.

Another thought: rendered markdown output with syntax highlighting would look nice.

**Comment by slochower** [comment]
> Another thought: rendered markdown output with syntax highlighting would look nice.

I suppose you could pipe the output to a Markdown file and then use something like this to render the Markdown in the terminal: http://brettterpstra.com/2015/08/21/mdless-better-markdown-in-terminal/ It seems there are a bunch of similar projects.
