### ISSUE TITLE
manubot cite date error with PMID citation

### ISSUE THREAD

**Issue by agitter** [greenelab/manubot#69]
I get an error with the following command
```
manubot cite pmid:29028984
```
Error:
```
conda\envs\manubot-dev\lib\site-packages\manubot\cite\pubmed.py", line 177, in extract_publication_date_parts
    date_parts.append(month_abbrev_to_int[month])
KeyError: '03'
```

This is manubot v0.2.0 from PyPI in the manubot-dev environment.  I didn't try debugging yet.

@dhimmel can you reproduce the error?

**Comment by agitter** [comment]
A quick look at the source indicates that the month was stored as `03` but `month_abbrev_to_int` dict expects a string.
https://github.com/greenelab/manubot/blob/9d97ec347882bcd85ab6aee7a3b4734105ebfc15/manubot/cite/pubmed.py#L138-L151

Here's the relevant part of the XML:
```
<JournalIssue CitedMedium="Internet">
    <Volume>34</Volume>
    <Issue>6</Issue>
    <PubDate>
	<Year>2018</Year>
	<Month>03</Month>
	<Day>15</Day>
    </PubDate>
</JournalIssue>
```

**Comment by dhimmel** [comment]
Ah geez, it seemed like there the PubMed schema coded months as 3-letter strings, but I guess this isn't universal. We can update the date parser to try `int` casting before falling back to the dict lookup.

**Comment by agitter** [comment]
Yeah, I was also surprised that it isn't universal.  I'm not sure what the relative frequency of the string versus integer month encoding is.  Should we catch the `KeyError` and try parsing to `int`?

I ask in case I find time for a quick pull request for this.

**Comment by dhimmel** [comment]
> I'm not sure what the relative frequency of the string versus integer month encoding is.

int seems to be much less common. Sure might as well catch KeyError first then try int casting.
